remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Mathematical Aspects of Data Science
description: Graduate Summer School - EPFL - Sept. 1-5, 2025
